name: installing, building, testing, linting
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  integration:
    # Среды для запуска job
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [17.x]
    # Система на которой будет запускаться job
    runs-on: ${{ matrix.os }}

    # Шаги представляют собой последовательность задач, которые будут выполняться как часть задания.
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: install node modules
        run: npm install

      - name: build production project
        run: npm run build:prod

      - name: linting ts
        run: npm run lint:ts

      - name: linting css
        run: npm run lint:scss

      - name: unit testing
        run: npm run test:unit